package utils;

public enum Ciudades {
	ALBACETE, ALICANTE, ALMERIA, AVILA,
	BADAJOZ, BARCELONA, BILBAO, BURGOS,
	CACERES, CADIZ, CASTELLON, CIUDAD_REAL, 
	CORDOBA, A_CORUNYA, CUENCA, GIRONA, 
	GRANADA, GUADALAJARA, HUELVA, HUESCA,
	JAEN, LEON, LLEIDA, LOGRONYO, 
	LUGO, MADRID, MALAGA, MURCIA;
}
